// Code generated by ent, DO NOT EDIT.

package category

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImageID holds the string denoting the image_id field in the database.
	FieldImageID = "image_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCosmetics holds the string denoting the cosmetics edge name in mutations.
	EdgeCosmetics = "cosmetics"
	// Table holds the table name of the category in the database.
	Table = "categories"
	// CosmeticsTable is the table that holds the cosmetics relation/edge.
	CosmeticsTable = "cosmetics"
	// CosmeticsInverseTable is the table name for the Cosmetics entity.
	// It exists in this package in order to avoid circular dependency with the "cosmetics" package.
	CosmeticsInverseTable = "cosmetics"
	// CosmeticsColumn is the table column denoting the cosmetics relation/edge.
	CosmeticsColumn = "category_cosmetics"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldImageID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Category queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImageID orders the results by the image_id field.
func ByImageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCosmeticsCount orders the results by cosmetics count.
func ByCosmeticsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCosmeticsStep(), opts...)
	}
}

// ByCosmetics orders the results by cosmetics terms.
func ByCosmetics(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCosmeticsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCosmeticsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CosmeticsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CosmeticsTable, CosmeticsColumn),
	)
}
