// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Cosmetics is the predicate function for cosmetics builders.
type Cosmetics func(*sql.Selector)

// MainPage is the predicate function for mainpage builders.
type MainPage func(*sql.Selector)

// News is the predicate function for news builders.
type News func(*sql.Selector)

// Partner is the predicate function for partner builders.
type Partner func(*sql.Selector)

// PartnerLink is the predicate function for partnerlink builders.
type PartnerLink func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
