// Code generated by ent, DO NOT EDIT.

package cosmetics

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the cosmetics type in the database.
	Label = "cosmetics"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImageID holds the string denoting the image_id field in the database.
	FieldImageID = "image_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldApplicationMethod holds the string denoting the applicationmethod field in the database.
	FieldApplicationMethod = "application_method"
	// FieldVolume holds the string denoting the volume field in the database.
	FieldVolume = "volume"
	// FieldOzonLink holds the string denoting the ozon_link field in the database.
	FieldOzonLink = "ozon_link"
	// FieldWildberriesLink holds the string denoting the wildberries_link field in the database.
	FieldWildberriesLink = "wildberries_link"
	// FieldIsHidden holds the string denoting the is_hidden field in the database.
	FieldIsHidden = "is_hidden"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// Table holds the table name of the cosmetics in the database.
	Table = "cosmetics"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "cosmetics"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_cosmetics"
)

// Columns holds all SQL columns for cosmetics fields.
var Columns = []string{
	FieldID,
	FieldImageID,
	FieldTitle,
	FieldDescription,
	FieldApplicationMethod,
	FieldVolume,
	FieldOzonLink,
	FieldWildberriesLink,
	FieldIsHidden,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "cosmetics"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"category_cosmetics",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// VolumeValidator is a validator for the "volume" field. It is called by the builders before save.
	VolumeValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Cosmetics queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImageID orders the results by the image_id field.
func ByImageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByApplicationMethod orders the results by the applicationMethod field.
func ByApplicationMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationMethod, opts...).ToFunc()
}

// ByVolume orders the results by the volume field.
func ByVolume(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVolume, opts...).ToFunc()
}

// ByOzonLink orders the results by the ozon_link field.
func ByOzonLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOzonLink, opts...).ToFunc()
}

// ByWildberriesLink orders the results by the wildberries_link field.
func ByWildberriesLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWildberriesLink, opts...).ToFunc()
}

// ByIsHidden orders the results by the is_hidden field.
func ByIsHidden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsHidden, opts...).ToFunc()
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
