// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "image_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// CosmeticsColumns holds the columns for the "cosmetics" table.
	CosmeticsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "image_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "application_method", Type: field.TypeString, Nullable: true},
		{Name: "volume", Type: field.TypeInt, Nullable: true},
		{Name: "ozon_link", Type: field.TypeString, Nullable: true},
		{Name: "wildberries_link", Type: field.TypeString, Nullable: true},
		{Name: "is_hidden", Type: field.TypeBool},
		{Name: "category_cosmetics", Type: field.TypeUUID},
	}
	// CosmeticsTable holds the schema information for the "cosmetics" table.
	CosmeticsTable = &schema.Table{
		Name:       "cosmetics",
		Columns:    CosmeticsColumns,
		PrimaryKey: []*schema.Column{CosmeticsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cosmetics_categories_cosmetics",
				Columns:    []*schema.Column{CosmeticsColumns[9]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "cosmetics_is_hidden",
				Unique:  false,
				Columns: []*schema.Column{CosmeticsColumns[8]},
			},
		},
	}
	// MainPagesColumns holds the columns for the "main_pages" table.
	MainPagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "image_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "href", Type: field.TypeString},
		{Name: "is_hidden", Type: field.TypeBool, Default: false},
		{Name: "fluid", Type: field.TypeBool, Default: false},
	}
	// MainPagesTable holds the schema information for the "main_pages" table.
	MainPagesTable = &schema.Table{
		Name:       "main_pages",
		Columns:    MainPagesColumns,
		PrimaryKey: []*schema.Column{MainPagesColumns[0]},
	}
	// NewsColumns holds the columns for the "news" table.
	NewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "image_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "is_hidden", Type: field.TypeBool},
	}
	// NewsTable holds the schema information for the "news" table.
	NewsTable = &schema.Table{
		Name:       "news",
		Columns:    NewsColumns,
		PrimaryKey: []*schema.Column{NewsColumns[0]},
	}
	// PartnersColumns holds the columns for the "partners" table.
	PartnersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
	}
	// PartnersTable holds the schema information for the "partners" table.
	PartnersTable = &schema.Table{
		Name:       "partners",
		Columns:    PartnersColumns,
		PrimaryKey: []*schema.Column{PartnersColumns[0]},
	}
	// PartnerLinksColumns holds the columns for the "partner_links" table.
	PartnerLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString},
		{Name: "href", Type: field.TypeString},
		{Name: "partner_links", Type: field.TypeUUID},
	}
	// PartnerLinksTable holds the schema information for the "partner_links" table.
	PartnerLinksTable = &schema.Table{
		Name:       "partner_links",
		Columns:    PartnerLinksColumns,
		PrimaryKey: []*schema.Column{PartnerLinksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "partner_links_partners_links",
				Columns:    []*schema.Column{PartnerLinksColumns[3]},
				RefColumns: []*schema.Column{PartnersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "jti", Type: field.TypeString},
		{Name: "user_refresh_tokens", Type: field.TypeUUID, Unique: true},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "surname", Type: field.TypeString, Size: 100},
		{Name: "role", Type: field.TypeInt, Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		CosmeticsTable,
		MainPagesTable,
		NewsTable,
		PartnersTable,
		PartnerLinksTable,
		RefreshTokensTable,
		UsersTable,
	}
)

func init() {
	CosmeticsTable.ForeignKeys[0].RefTable = CategoriesTable
	PartnerLinksTable.ForeignKeys[0].RefTable = PartnersTable
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
}
