// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/category"
	"SmartLeague/pkg/ent/cosmetics"
	"SmartLeague/pkg/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CosmeticsQuery is the builder for querying Cosmetics entities.
type CosmeticsQuery struct {
	config
	ctx          *QueryContext
	order        []cosmetics.OrderOption
	inters       []Interceptor
	predicates   []predicate.Cosmetics
	withCategory *CategoryQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CosmeticsQuery builder.
func (cq *CosmeticsQuery) Where(ps ...predicate.Cosmetics) *CosmeticsQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CosmeticsQuery) Limit(limit int) *CosmeticsQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CosmeticsQuery) Offset(offset int) *CosmeticsQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CosmeticsQuery) Unique(unique bool) *CosmeticsQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CosmeticsQuery) Order(o ...cosmetics.OrderOption) *CosmeticsQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryCategory chains the current query on the "category" edge.
func (cq *CosmeticsQuery) QueryCategory() *CategoryQuery {
	query := (&CategoryClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cosmetics.Table, cosmetics.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cosmetics.CategoryTable, cosmetics.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Cosmetics entity from the query.
// Returns a *NotFoundError when no Cosmetics was found.
func (cq *CosmeticsQuery) First(ctx context.Context) (*Cosmetics, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cosmetics.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CosmeticsQuery) FirstX(ctx context.Context) *Cosmetics {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Cosmetics ID from the query.
// Returns a *NotFoundError when no Cosmetics ID was found.
func (cq *CosmeticsQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cosmetics.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CosmeticsQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Cosmetics entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Cosmetics entity is found.
// Returns a *NotFoundError when no Cosmetics entities are found.
func (cq *CosmeticsQuery) Only(ctx context.Context) (*Cosmetics, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cosmetics.Label}
	default:
		return nil, &NotSingularError{cosmetics.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CosmeticsQuery) OnlyX(ctx context.Context) *Cosmetics {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Cosmetics ID in the query.
// Returns a *NotSingularError when more than one Cosmetics ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CosmeticsQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cosmetics.Label}
	default:
		err = &NotSingularError{cosmetics.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CosmeticsQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CosmeticsSlice.
func (cq *CosmeticsQuery) All(ctx context.Context) ([]*Cosmetics, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Cosmetics, *CosmeticsQuery]()
	return withInterceptors[[]*Cosmetics](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CosmeticsQuery) AllX(ctx context.Context) []*Cosmetics {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Cosmetics IDs.
func (cq *CosmeticsQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(cosmetics.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CosmeticsQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CosmeticsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CosmeticsQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CosmeticsQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CosmeticsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CosmeticsQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CosmeticsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CosmeticsQuery) Clone() *CosmeticsQuery {
	if cq == nil {
		return nil
	}
	return &CosmeticsQuery{
		config:       cq.config,
		ctx:          cq.ctx.Clone(),
		order:        append([]cosmetics.OrderOption{}, cq.order...),
		inters:       append([]Interceptor{}, cq.inters...),
		predicates:   append([]predicate.Cosmetics{}, cq.predicates...),
		withCategory: cq.withCategory.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CosmeticsQuery) WithCategory(opts ...func(*CategoryQuery)) *CosmeticsQuery {
	query := (&CategoryClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withCategory = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ImageID uuid.UUID `json:"image_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Cosmetics.Query().
//		GroupBy(cosmetics.FieldImageID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CosmeticsQuery) GroupBy(field string, fields ...string) *CosmeticsGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CosmeticsGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = cosmetics.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ImageID uuid.UUID `json:"image_id,omitempty"`
//	}
//
//	client.Cosmetics.Query().
//		Select(cosmetics.FieldImageID).
//		Scan(ctx, &v)
func (cq *CosmeticsQuery) Select(fields ...string) *CosmeticsSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CosmeticsSelect{CosmeticsQuery: cq}
	sbuild.label = cosmetics.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CosmeticsSelect configured with the given aggregations.
func (cq *CosmeticsQuery) Aggregate(fns ...AggregateFunc) *CosmeticsSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CosmeticsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !cosmetics.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CosmeticsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Cosmetics, error) {
	var (
		nodes       = []*Cosmetics{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withCategory != nil,
		}
	)
	if cq.withCategory != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, cosmetics.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Cosmetics).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Cosmetics{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withCategory; query != nil {
		if err := cq.loadCategory(ctx, query, nodes, nil,
			func(n *Cosmetics, e *Category) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CosmeticsQuery) loadCategory(ctx context.Context, query *CategoryQuery, nodes []*Cosmetics, init func(*Cosmetics), assign func(*Cosmetics, *Category)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Cosmetics)
	for i := range nodes {
		if nodes[i].category_cosmetics == nil {
			continue
		}
		fk := *nodes[i].category_cosmetics
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(category.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_cosmetics" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cq *CosmeticsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CosmeticsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cosmetics.Table, cosmetics.Columns, sqlgraph.NewFieldSpec(cosmetics.FieldID, field.TypeUUID))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cosmetics.FieldID)
		for i := range fields {
			if fields[i] != cosmetics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CosmeticsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(cosmetics.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = cosmetics.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CosmeticsGroupBy is the group-by builder for Cosmetics entities.
type CosmeticsGroupBy struct {
	selector
	build *CosmeticsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CosmeticsGroupBy) Aggregate(fns ...AggregateFunc) *CosmeticsGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CosmeticsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CosmeticsQuery, *CosmeticsGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CosmeticsGroupBy) sqlScan(ctx context.Context, root *CosmeticsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CosmeticsSelect is the builder for selecting fields of Cosmetics entities.
type CosmeticsSelect struct {
	*CosmeticsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CosmeticsSelect) Aggregate(fns ...AggregateFunc) *CosmeticsSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CosmeticsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CosmeticsQuery, *CosmeticsSelect](ctx, cs.CosmeticsQuery, cs, cs.inters, v)
}

func (cs *CosmeticsSelect) sqlScan(ctx context.Context, root *CosmeticsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
