// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/category"
	"SmartLeague/pkg/ent/cosmetics"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Cosmetics is the model entity for the Cosmetics schema.
type Cosmetics struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ImageID holds the value of the "image_id" field.
	ImageID uuid.UUID `json:"image_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// ApplicationMethod holds the value of the "applicationMethod" field.
	ApplicationMethod *string `json:"applicationMethod,omitempty"`
	// Volume holds the value of the "volume" field.
	Volume *int `json:"volume,omitempty"`
	// OzonLink holds the value of the "ozon_link" field.
	OzonLink *string `json:"ozon_link,omitempty"`
	// WildberriesLink holds the value of the "wildberries_link" field.
	WildberriesLink *string `json:"wildberries_link,omitempty"`
	// IsHidden holds the value of the "is_hidden" field.
	IsHidden bool `json:"is_hidden,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CosmeticsQuery when eager-loading is set.
	Edges              CosmeticsEdges `json:"edges"`
	category_cosmetics *uuid.UUID
	selectValues       sql.SelectValues
}

// CosmeticsEdges holds the relations/edges for other nodes in the graph.
type CosmeticsEdges struct {
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CosmeticsEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cosmetics) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cosmetics.FieldIsHidden:
			values[i] = new(sql.NullBool)
		case cosmetics.FieldVolume:
			values[i] = new(sql.NullInt64)
		case cosmetics.FieldTitle, cosmetics.FieldDescription, cosmetics.FieldApplicationMethod, cosmetics.FieldOzonLink, cosmetics.FieldWildberriesLink:
			values[i] = new(sql.NullString)
		case cosmetics.FieldID, cosmetics.FieldImageID:
			values[i] = new(uuid.UUID)
		case cosmetics.ForeignKeys[0]: // category_cosmetics
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cosmetics fields.
func (c *Cosmetics) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cosmetics.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				c.ID = *value
			}
		case cosmetics.FieldImageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field image_id", values[i])
			} else if value != nil {
				c.ImageID = *value
			}
		case cosmetics.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				c.Title = value.String
			}
		case cosmetics.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				c.Description = new(string)
				*c.Description = value.String
			}
		case cosmetics.FieldApplicationMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field applicationMethod", values[i])
			} else if value.Valid {
				c.ApplicationMethod = new(string)
				*c.ApplicationMethod = value.String
			}
		case cosmetics.FieldVolume:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field volume", values[i])
			} else if value.Valid {
				c.Volume = new(int)
				*c.Volume = int(value.Int64)
			}
		case cosmetics.FieldOzonLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ozon_link", values[i])
			} else if value.Valid {
				c.OzonLink = new(string)
				*c.OzonLink = value.String
			}
		case cosmetics.FieldWildberriesLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wildberries_link", values[i])
			} else if value.Valid {
				c.WildberriesLink = new(string)
				*c.WildberriesLink = value.String
			}
		case cosmetics.FieldIsHidden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_hidden", values[i])
			} else if value.Valid {
				c.IsHidden = value.Bool
			}
		case cosmetics.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field category_cosmetics", values[i])
			} else if value.Valid {
				c.category_cosmetics = new(uuid.UUID)
				*c.category_cosmetics = *value.S.(*uuid.UUID)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Cosmetics.
// This includes values selected through modifiers, order, etc.
func (c *Cosmetics) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the Cosmetics entity.
func (c *Cosmetics) QueryCategory() *CategoryQuery {
	return NewCosmeticsClient(c.config).QueryCategory(c)
}

// Update returns a builder for updating this Cosmetics.
// Note that you need to call Cosmetics.Unwrap() before calling this method if this Cosmetics
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Cosmetics) Update() *CosmeticsUpdateOne {
	return NewCosmeticsClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Cosmetics entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Cosmetics) Unwrap() *Cosmetics {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cosmetics is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Cosmetics) String() string {
	var builder strings.Builder
	builder.WriteString("Cosmetics(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("image_id=")
	builder.WriteString(fmt.Sprintf("%v", c.ImageID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(c.Title)
	builder.WriteString(", ")
	if v := c.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := c.ApplicationMethod; v != nil {
		builder.WriteString("applicationMethod=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := c.Volume; v != nil {
		builder.WriteString("volume=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := c.OzonLink; v != nil {
		builder.WriteString("ozon_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := c.WildberriesLink; v != nil {
		builder.WriteString("wildberries_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_hidden=")
	builder.WriteString(fmt.Sprintf("%v", c.IsHidden))
	builder.WriteByte(')')
	return builder.String()
}

// CosmeticsSlice is a parsable slice of Cosmetics.
type CosmeticsSlice []*Cosmetics
