// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/mainpage"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MainPageCreate is the builder for creating a MainPage entity.
type MainPageCreate struct {
	config
	mutation *MainPageMutation
	hooks    []Hook
}

// SetImageID sets the "image_id" field.
func (mpc *MainPageCreate) SetImageID(u uuid.UUID) *MainPageCreate {
	mpc.mutation.SetImageID(u)
	return mpc
}

// SetTitle sets the "title" field.
func (mpc *MainPageCreate) SetTitle(s string) *MainPageCreate {
	mpc.mutation.SetTitle(s)
	return mpc
}

// SetContent sets the "content" field.
func (mpc *MainPageCreate) SetContent(s string) *MainPageCreate {
	mpc.mutation.SetContent(s)
	return mpc
}

// SetHref sets the "Href" field.
func (mpc *MainPageCreate) SetHref(s string) *MainPageCreate {
	mpc.mutation.SetHref(s)
	return mpc
}

// SetIsHidden sets the "IsHidden" field.
func (mpc *MainPageCreate) SetIsHidden(b bool) *MainPageCreate {
	mpc.mutation.SetIsHidden(b)
	return mpc
}

// SetNillableIsHidden sets the "IsHidden" field if the given value is not nil.
func (mpc *MainPageCreate) SetNillableIsHidden(b *bool) *MainPageCreate {
	if b != nil {
		mpc.SetIsHidden(*b)
	}
	return mpc
}

// SetFluid sets the "fluid" field.
func (mpc *MainPageCreate) SetFluid(b bool) *MainPageCreate {
	mpc.mutation.SetFluid(b)
	return mpc
}

// SetNillableFluid sets the "fluid" field if the given value is not nil.
func (mpc *MainPageCreate) SetNillableFluid(b *bool) *MainPageCreate {
	if b != nil {
		mpc.SetFluid(*b)
	}
	return mpc
}

// SetID sets the "id" field.
func (mpc *MainPageCreate) SetID(u uuid.UUID) *MainPageCreate {
	mpc.mutation.SetID(u)
	return mpc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mpc *MainPageCreate) SetNillableID(u *uuid.UUID) *MainPageCreate {
	if u != nil {
		mpc.SetID(*u)
	}
	return mpc
}

// Mutation returns the MainPageMutation object of the builder.
func (mpc *MainPageCreate) Mutation() *MainPageMutation {
	return mpc.mutation
}

// Save creates the MainPage in the database.
func (mpc *MainPageCreate) Save(ctx context.Context) (*MainPage, error) {
	mpc.defaults()
	return withHooks(ctx, mpc.sqlSave, mpc.mutation, mpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mpc *MainPageCreate) SaveX(ctx context.Context) *MainPage {
	v, err := mpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpc *MainPageCreate) Exec(ctx context.Context) error {
	_, err := mpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpc *MainPageCreate) ExecX(ctx context.Context) {
	if err := mpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpc *MainPageCreate) defaults() {
	if _, ok := mpc.mutation.IsHidden(); !ok {
		v := mainpage.DefaultIsHidden
		mpc.mutation.SetIsHidden(v)
	}
	if _, ok := mpc.mutation.Fluid(); !ok {
		v := mainpage.DefaultFluid
		mpc.mutation.SetFluid(v)
	}
	if _, ok := mpc.mutation.ID(); !ok {
		v := mainpage.DefaultID()
		mpc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpc *MainPageCreate) check() error {
	if _, ok := mpc.mutation.ImageID(); !ok {
		return &ValidationError{Name: "image_id", err: errors.New(`ent: missing required field "MainPage.image_id"`)}
	}
	if _, ok := mpc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "MainPage.title"`)}
	}
	if v, ok := mpc.mutation.Title(); ok {
		if err := mainpage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MainPage.title": %w`, err)}
		}
	}
	if _, ok := mpc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "MainPage.content"`)}
	}
	if v, ok := mpc.mutation.Content(); ok {
		if err := mainpage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "MainPage.content": %w`, err)}
		}
	}
	if _, ok := mpc.mutation.Href(); !ok {
		return &ValidationError{Name: "Href", err: errors.New(`ent: missing required field "MainPage.Href"`)}
	}
	if v, ok := mpc.mutation.Href(); ok {
		if err := mainpage.HrefValidator(v); err != nil {
			return &ValidationError{Name: "Href", err: fmt.Errorf(`ent: validator failed for field "MainPage.Href": %w`, err)}
		}
	}
	if _, ok := mpc.mutation.IsHidden(); !ok {
		return &ValidationError{Name: "IsHidden", err: errors.New(`ent: missing required field "MainPage.IsHidden"`)}
	}
	if _, ok := mpc.mutation.Fluid(); !ok {
		return &ValidationError{Name: "fluid", err: errors.New(`ent: missing required field "MainPage.fluid"`)}
	}
	return nil
}

func (mpc *MainPageCreate) sqlSave(ctx context.Context) (*MainPage, error) {
	if err := mpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mpc.mutation.id = &_node.ID
	mpc.mutation.done = true
	return _node, nil
}

func (mpc *MainPageCreate) createSpec() (*MainPage, *sqlgraph.CreateSpec) {
	var (
		_node = &MainPage{config: mpc.config}
		_spec = sqlgraph.NewCreateSpec(mainpage.Table, sqlgraph.NewFieldSpec(mainpage.FieldID, field.TypeUUID))
	)
	if id, ok := mpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mpc.mutation.ImageID(); ok {
		_spec.SetField(mainpage.FieldImageID, field.TypeUUID, value)
		_node.ImageID = value
	}
	if value, ok := mpc.mutation.Title(); ok {
		_spec.SetField(mainpage.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mpc.mutation.Content(); ok {
		_spec.SetField(mainpage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := mpc.mutation.Href(); ok {
		_spec.SetField(mainpage.FieldHref, field.TypeString, value)
		_node.Href = value
	}
	if value, ok := mpc.mutation.IsHidden(); ok {
		_spec.SetField(mainpage.FieldIsHidden, field.TypeBool, value)
		_node.IsHidden = value
	}
	if value, ok := mpc.mutation.Fluid(); ok {
		_spec.SetField(mainpage.FieldFluid, field.TypeBool, value)
		_node.Fluid = value
	}
	return _node, _spec
}

// MainPageCreateBulk is the builder for creating many MainPage entities in bulk.
type MainPageCreateBulk struct {
	config
	err      error
	builders []*MainPageCreate
}

// Save creates the MainPage entities in the database.
func (mpcb *MainPageCreateBulk) Save(ctx context.Context) ([]*MainPage, error) {
	if mpcb.err != nil {
		return nil, mpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mpcb.builders))
	nodes := make([]*MainPage, len(mpcb.builders))
	mutators := make([]Mutator, len(mpcb.builders))
	for i := range mpcb.builders {
		func(i int, root context.Context) {
			builder := mpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MainPageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mpcb *MainPageCreateBulk) SaveX(ctx context.Context) []*MainPage {
	v, err := mpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpcb *MainPageCreateBulk) Exec(ctx context.Context) error {
	_, err := mpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpcb *MainPageCreateBulk) ExecX(ctx context.Context) {
	if err := mpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
