// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/mainpage"
	"SmartLeague/pkg/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MainPageUpdate is the builder for updating MainPage entities.
type MainPageUpdate struct {
	config
	hooks    []Hook
	mutation *MainPageMutation
}

// Where appends a list predicates to the MainPageUpdate builder.
func (mpu *MainPageUpdate) Where(ps ...predicate.MainPage) *MainPageUpdate {
	mpu.mutation.Where(ps...)
	return mpu
}

// SetImageID sets the "image_id" field.
func (mpu *MainPageUpdate) SetImageID(u uuid.UUID) *MainPageUpdate {
	mpu.mutation.SetImageID(u)
	return mpu
}

// SetNillableImageID sets the "image_id" field if the given value is not nil.
func (mpu *MainPageUpdate) SetNillableImageID(u *uuid.UUID) *MainPageUpdate {
	if u != nil {
		mpu.SetImageID(*u)
	}
	return mpu
}

// SetTitle sets the "title" field.
func (mpu *MainPageUpdate) SetTitle(s string) *MainPageUpdate {
	mpu.mutation.SetTitle(s)
	return mpu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mpu *MainPageUpdate) SetNillableTitle(s *string) *MainPageUpdate {
	if s != nil {
		mpu.SetTitle(*s)
	}
	return mpu
}

// SetContent sets the "content" field.
func (mpu *MainPageUpdate) SetContent(s string) *MainPageUpdate {
	mpu.mutation.SetContent(s)
	return mpu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (mpu *MainPageUpdate) SetNillableContent(s *string) *MainPageUpdate {
	if s != nil {
		mpu.SetContent(*s)
	}
	return mpu
}

// SetHref sets the "Href" field.
func (mpu *MainPageUpdate) SetHref(s string) *MainPageUpdate {
	mpu.mutation.SetHref(s)
	return mpu
}

// SetNillableHref sets the "Href" field if the given value is not nil.
func (mpu *MainPageUpdate) SetNillableHref(s *string) *MainPageUpdate {
	if s != nil {
		mpu.SetHref(*s)
	}
	return mpu
}

// SetIsHidden sets the "IsHidden" field.
func (mpu *MainPageUpdate) SetIsHidden(b bool) *MainPageUpdate {
	mpu.mutation.SetIsHidden(b)
	return mpu
}

// SetNillableIsHidden sets the "IsHidden" field if the given value is not nil.
func (mpu *MainPageUpdate) SetNillableIsHidden(b *bool) *MainPageUpdate {
	if b != nil {
		mpu.SetIsHidden(*b)
	}
	return mpu
}

// SetFluid sets the "fluid" field.
func (mpu *MainPageUpdate) SetFluid(b bool) *MainPageUpdate {
	mpu.mutation.SetFluid(b)
	return mpu
}

// SetNillableFluid sets the "fluid" field if the given value is not nil.
func (mpu *MainPageUpdate) SetNillableFluid(b *bool) *MainPageUpdate {
	if b != nil {
		mpu.SetFluid(*b)
	}
	return mpu
}

// Mutation returns the MainPageMutation object of the builder.
func (mpu *MainPageUpdate) Mutation() *MainPageMutation {
	return mpu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mpu *MainPageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mpu.sqlSave, mpu.mutation, mpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mpu *MainPageUpdate) SaveX(ctx context.Context) int {
	affected, err := mpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mpu *MainPageUpdate) Exec(ctx context.Context) error {
	_, err := mpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpu *MainPageUpdate) ExecX(ctx context.Context) {
	if err := mpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpu *MainPageUpdate) check() error {
	if v, ok := mpu.mutation.Title(); ok {
		if err := mainpage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MainPage.title": %w`, err)}
		}
	}
	if v, ok := mpu.mutation.Content(); ok {
		if err := mainpage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "MainPage.content": %w`, err)}
		}
	}
	if v, ok := mpu.mutation.Href(); ok {
		if err := mainpage.HrefValidator(v); err != nil {
			return &ValidationError{Name: "Href", err: fmt.Errorf(`ent: validator failed for field "MainPage.Href": %w`, err)}
		}
	}
	return nil
}

func (mpu *MainPageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(mainpage.Table, mainpage.Columns, sqlgraph.NewFieldSpec(mainpage.FieldID, field.TypeUUID))
	if ps := mpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpu.mutation.ImageID(); ok {
		_spec.SetField(mainpage.FieldImageID, field.TypeUUID, value)
	}
	if value, ok := mpu.mutation.Title(); ok {
		_spec.SetField(mainpage.FieldTitle, field.TypeString, value)
	}
	if value, ok := mpu.mutation.Content(); ok {
		_spec.SetField(mainpage.FieldContent, field.TypeString, value)
	}
	if value, ok := mpu.mutation.Href(); ok {
		_spec.SetField(mainpage.FieldHref, field.TypeString, value)
	}
	if value, ok := mpu.mutation.IsHidden(); ok {
		_spec.SetField(mainpage.FieldIsHidden, field.TypeBool, value)
	}
	if value, ok := mpu.mutation.Fluid(); ok {
		_spec.SetField(mainpage.FieldFluid, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mainpage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mpu.mutation.done = true
	return n, nil
}

// MainPageUpdateOne is the builder for updating a single MainPage entity.
type MainPageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MainPageMutation
}

// SetImageID sets the "image_id" field.
func (mpuo *MainPageUpdateOne) SetImageID(u uuid.UUID) *MainPageUpdateOne {
	mpuo.mutation.SetImageID(u)
	return mpuo
}

// SetNillableImageID sets the "image_id" field if the given value is not nil.
func (mpuo *MainPageUpdateOne) SetNillableImageID(u *uuid.UUID) *MainPageUpdateOne {
	if u != nil {
		mpuo.SetImageID(*u)
	}
	return mpuo
}

// SetTitle sets the "title" field.
func (mpuo *MainPageUpdateOne) SetTitle(s string) *MainPageUpdateOne {
	mpuo.mutation.SetTitle(s)
	return mpuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mpuo *MainPageUpdateOne) SetNillableTitle(s *string) *MainPageUpdateOne {
	if s != nil {
		mpuo.SetTitle(*s)
	}
	return mpuo
}

// SetContent sets the "content" field.
func (mpuo *MainPageUpdateOne) SetContent(s string) *MainPageUpdateOne {
	mpuo.mutation.SetContent(s)
	return mpuo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (mpuo *MainPageUpdateOne) SetNillableContent(s *string) *MainPageUpdateOne {
	if s != nil {
		mpuo.SetContent(*s)
	}
	return mpuo
}

// SetHref sets the "Href" field.
func (mpuo *MainPageUpdateOne) SetHref(s string) *MainPageUpdateOne {
	mpuo.mutation.SetHref(s)
	return mpuo
}

// SetNillableHref sets the "Href" field if the given value is not nil.
func (mpuo *MainPageUpdateOne) SetNillableHref(s *string) *MainPageUpdateOne {
	if s != nil {
		mpuo.SetHref(*s)
	}
	return mpuo
}

// SetIsHidden sets the "IsHidden" field.
func (mpuo *MainPageUpdateOne) SetIsHidden(b bool) *MainPageUpdateOne {
	mpuo.mutation.SetIsHidden(b)
	return mpuo
}

// SetNillableIsHidden sets the "IsHidden" field if the given value is not nil.
func (mpuo *MainPageUpdateOne) SetNillableIsHidden(b *bool) *MainPageUpdateOne {
	if b != nil {
		mpuo.SetIsHidden(*b)
	}
	return mpuo
}

// SetFluid sets the "fluid" field.
func (mpuo *MainPageUpdateOne) SetFluid(b bool) *MainPageUpdateOne {
	mpuo.mutation.SetFluid(b)
	return mpuo
}

// SetNillableFluid sets the "fluid" field if the given value is not nil.
func (mpuo *MainPageUpdateOne) SetNillableFluid(b *bool) *MainPageUpdateOne {
	if b != nil {
		mpuo.SetFluid(*b)
	}
	return mpuo
}

// Mutation returns the MainPageMutation object of the builder.
func (mpuo *MainPageUpdateOne) Mutation() *MainPageMutation {
	return mpuo.mutation
}

// Where appends a list predicates to the MainPageUpdate builder.
func (mpuo *MainPageUpdateOne) Where(ps ...predicate.MainPage) *MainPageUpdateOne {
	mpuo.mutation.Where(ps...)
	return mpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mpuo *MainPageUpdateOne) Select(field string, fields ...string) *MainPageUpdateOne {
	mpuo.fields = append([]string{field}, fields...)
	return mpuo
}

// Save executes the query and returns the updated MainPage entity.
func (mpuo *MainPageUpdateOne) Save(ctx context.Context) (*MainPage, error) {
	return withHooks(ctx, mpuo.sqlSave, mpuo.mutation, mpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mpuo *MainPageUpdateOne) SaveX(ctx context.Context) *MainPage {
	node, err := mpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mpuo *MainPageUpdateOne) Exec(ctx context.Context) error {
	_, err := mpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpuo *MainPageUpdateOne) ExecX(ctx context.Context) {
	if err := mpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpuo *MainPageUpdateOne) check() error {
	if v, ok := mpuo.mutation.Title(); ok {
		if err := mainpage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MainPage.title": %w`, err)}
		}
	}
	if v, ok := mpuo.mutation.Content(); ok {
		if err := mainpage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "MainPage.content": %w`, err)}
		}
	}
	if v, ok := mpuo.mutation.Href(); ok {
		if err := mainpage.HrefValidator(v); err != nil {
			return &ValidationError{Name: "Href", err: fmt.Errorf(`ent: validator failed for field "MainPage.Href": %w`, err)}
		}
	}
	return nil
}

func (mpuo *MainPageUpdateOne) sqlSave(ctx context.Context) (_node *MainPage, err error) {
	if err := mpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mainpage.Table, mainpage.Columns, sqlgraph.NewFieldSpec(mainpage.FieldID, field.TypeUUID))
	id, ok := mpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MainPage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mainpage.FieldID)
		for _, f := range fields {
			if !mainpage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mainpage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpuo.mutation.ImageID(); ok {
		_spec.SetField(mainpage.FieldImageID, field.TypeUUID, value)
	}
	if value, ok := mpuo.mutation.Title(); ok {
		_spec.SetField(mainpage.FieldTitle, field.TypeString, value)
	}
	if value, ok := mpuo.mutation.Content(); ok {
		_spec.SetField(mainpage.FieldContent, field.TypeString, value)
	}
	if value, ok := mpuo.mutation.Href(); ok {
		_spec.SetField(mainpage.FieldHref, field.TypeString, value)
	}
	if value, ok := mpuo.mutation.IsHidden(); ok {
		_spec.SetField(mainpage.FieldIsHidden, field.TypeBool, value)
	}
	if value, ok := mpuo.mutation.Fluid(); ok {
		_spec.SetField(mainpage.FieldFluid, field.TypeBool, value)
	}
	_node = &MainPage{config: mpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mainpage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mpuo.mutation.done = true
	return _node, nil
}
