// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/mainpage"
	"SmartLeague/pkg/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MainPageDelete is the builder for deleting a MainPage entity.
type MainPageDelete struct {
	config
	hooks    []Hook
	mutation *MainPageMutation
}

// Where appends a list predicates to the MainPageDelete builder.
func (mpd *MainPageDelete) Where(ps ...predicate.MainPage) *MainPageDelete {
	mpd.mutation.Where(ps...)
	return mpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpd *MainPageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mpd.sqlExec, mpd.mutation, mpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mpd *MainPageDelete) ExecX(ctx context.Context) int {
	n, err := mpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpd *MainPageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mainpage.Table, sqlgraph.NewFieldSpec(mainpage.FieldID, field.TypeUUID))
	if ps := mpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mpd.mutation.done = true
	return affected, err
}

// MainPageDeleteOne is the builder for deleting a single MainPage entity.
type MainPageDeleteOne struct {
	mpd *MainPageDelete
}

// Where appends a list predicates to the MainPageDelete builder.
func (mpdo *MainPageDeleteOne) Where(ps ...predicate.MainPage) *MainPageDeleteOne {
	mpdo.mpd.mutation.Where(ps...)
	return mpdo
}

// Exec executes the deletion query.
func (mpdo *MainPageDeleteOne) Exec(ctx context.Context) error {
	n, err := mpdo.mpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mainpage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdo *MainPageDeleteOne) ExecX(ctx context.Context) {
	if err := mpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
