// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/mainpage"
	"SmartLeague/pkg/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MainPageQuery is the builder for querying MainPage entities.
type MainPageQuery struct {
	config
	ctx        *QueryContext
	order      []mainpage.OrderOption
	inters     []Interceptor
	predicates []predicate.MainPage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MainPageQuery builder.
func (mpq *MainPageQuery) Where(ps ...predicate.MainPage) *MainPageQuery {
	mpq.predicates = append(mpq.predicates, ps...)
	return mpq
}

// Limit the number of records to be returned by this query.
func (mpq *MainPageQuery) Limit(limit int) *MainPageQuery {
	mpq.ctx.Limit = &limit
	return mpq
}

// Offset to start from.
func (mpq *MainPageQuery) Offset(offset int) *MainPageQuery {
	mpq.ctx.Offset = &offset
	return mpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpq *MainPageQuery) Unique(unique bool) *MainPageQuery {
	mpq.ctx.Unique = &unique
	return mpq
}

// Order specifies how the records should be ordered.
func (mpq *MainPageQuery) Order(o ...mainpage.OrderOption) *MainPageQuery {
	mpq.order = append(mpq.order, o...)
	return mpq
}

// First returns the first MainPage entity from the query.
// Returns a *NotFoundError when no MainPage was found.
func (mpq *MainPageQuery) First(ctx context.Context) (*MainPage, error) {
	nodes, err := mpq.Limit(1).All(setContextOp(ctx, mpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mainpage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpq *MainPageQuery) FirstX(ctx context.Context) *MainPage {
	node, err := mpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MainPage ID from the query.
// Returns a *NotFoundError when no MainPage ID was found.
func (mpq *MainPageQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpq.Limit(1).IDs(setContextOp(ctx, mpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mainpage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpq *MainPageQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MainPage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MainPage entity is found.
// Returns a *NotFoundError when no MainPage entities are found.
func (mpq *MainPageQuery) Only(ctx context.Context) (*MainPage, error) {
	nodes, err := mpq.Limit(2).All(setContextOp(ctx, mpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mainpage.Label}
	default:
		return nil, &NotSingularError{mainpage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpq *MainPageQuery) OnlyX(ctx context.Context) *MainPage {
	node, err := mpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MainPage ID in the query.
// Returns a *NotSingularError when more than one MainPage ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpq *MainPageQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mpq.Limit(2).IDs(setContextOp(ctx, mpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mainpage.Label}
	default:
		err = &NotSingularError{mainpage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpq *MainPageQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MainPages.
func (mpq *MainPageQuery) All(ctx context.Context) ([]*MainPage, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryAll)
	if err := mpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MainPage, *MainPageQuery]()
	return withInterceptors[[]*MainPage](ctx, mpq, qr, mpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mpq *MainPageQuery) AllX(ctx context.Context) []*MainPage {
	nodes, err := mpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MainPage IDs.
func (mpq *MainPageQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if mpq.ctx.Unique == nil && mpq.path != nil {
		mpq.Unique(true)
	}
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryIDs)
	if err = mpq.Select(mainpage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpq *MainPageQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpq *MainPageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryCount)
	if err := mpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mpq, querierCount[*MainPageQuery](), mpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mpq *MainPageQuery) CountX(ctx context.Context) int {
	count, err := mpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpq *MainPageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryExist)
	switch _, err := mpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mpq *MainPageQuery) ExistX(ctx context.Context) bool {
	exist, err := mpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MainPageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpq *MainPageQuery) Clone() *MainPageQuery {
	if mpq == nil {
		return nil
	}
	return &MainPageQuery{
		config:     mpq.config,
		ctx:        mpq.ctx.Clone(),
		order:      append([]mainpage.OrderOption{}, mpq.order...),
		inters:     append([]Interceptor{}, mpq.inters...),
		predicates: append([]predicate.MainPage{}, mpq.predicates...),
		// clone intermediate query.
		sql:  mpq.sql.Clone(),
		path: mpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ImageID uuid.UUID `json:"image_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MainPage.Query().
//		GroupBy(mainpage.FieldImageID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mpq *MainPageQuery) GroupBy(field string, fields ...string) *MainPageGroupBy {
	mpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MainPageGroupBy{build: mpq}
	grbuild.flds = &mpq.ctx.Fields
	grbuild.label = mainpage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ImageID uuid.UUID `json:"image_id,omitempty"`
//	}
//
//	client.MainPage.Query().
//		Select(mainpage.FieldImageID).
//		Scan(ctx, &v)
func (mpq *MainPageQuery) Select(fields ...string) *MainPageSelect {
	mpq.ctx.Fields = append(mpq.ctx.Fields, fields...)
	sbuild := &MainPageSelect{MainPageQuery: mpq}
	sbuild.label = mainpage.Label
	sbuild.flds, sbuild.scan = &mpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MainPageSelect configured with the given aggregations.
func (mpq *MainPageQuery) Aggregate(fns ...AggregateFunc) *MainPageSelect {
	return mpq.Select().Aggregate(fns...)
}

func (mpq *MainPageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mpq); err != nil {
				return err
			}
		}
	}
	for _, f := range mpq.ctx.Fields {
		if !mainpage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpq.path != nil {
		prev, err := mpq.path(ctx)
		if err != nil {
			return err
		}
		mpq.sql = prev
	}
	return nil
}

func (mpq *MainPageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MainPage, error) {
	var (
		nodes = []*MainPage{}
		_spec = mpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MainPage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MainPage{config: mpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mpq *MainPageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpq.querySpec()
	_spec.Node.Columns = mpq.ctx.Fields
	if len(mpq.ctx.Fields) > 0 {
		_spec.Unique = mpq.ctx.Unique != nil && *mpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mpq.driver, _spec)
}

func (mpq *MainPageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mainpage.Table, mainpage.Columns, sqlgraph.NewFieldSpec(mainpage.FieldID, field.TypeUUID))
	_spec.From = mpq.sql
	if unique := mpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mpq.path != nil {
		_spec.Unique = true
	}
	if fields := mpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mainpage.FieldID)
		for i := range fields {
			if fields[i] != mainpage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpq *MainPageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpq.driver.Dialect())
	t1 := builder.Table(mainpage.Table)
	columns := mpq.ctx.Fields
	if len(columns) == 0 {
		columns = mainpage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpq.sql != nil {
		selector = mpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpq.ctx.Unique != nil && *mpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mpq.predicates {
		p(selector)
	}
	for _, p := range mpq.order {
		p(selector)
	}
	if offset := mpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MainPageGroupBy is the group-by builder for MainPage entities.
type MainPageGroupBy struct {
	selector
	build *MainPageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpgb *MainPageGroupBy) Aggregate(fns ...AggregateFunc) *MainPageGroupBy {
	mpgb.fns = append(mpgb.fns, fns...)
	return mpgb
}

// Scan applies the selector query and scans the result into the given value.
func (mpgb *MainPageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mpgb.build.ctx, ent.OpQueryGroupBy)
	if err := mpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MainPageQuery, *MainPageGroupBy](ctx, mpgb.build, mpgb, mpgb.build.inters, v)
}

func (mpgb *MainPageGroupBy) sqlScan(ctx context.Context, root *MainPageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mpgb.fns))
	for _, fn := range mpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mpgb.flds)+len(mpgb.fns))
		for _, f := range *mpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MainPageSelect is the builder for selecting fields of MainPage entities.
type MainPageSelect struct {
	*MainPageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mps *MainPageSelect) Aggregate(fns ...AggregateFunc) *MainPageSelect {
	mps.fns = append(mps.fns, fns...)
	return mps
}

// Scan applies the selector query and scans the result into the given value.
func (mps *MainPageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mps.ctx, ent.OpQuerySelect)
	if err := mps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MainPageQuery, *MainPageSelect](ctx, mps.MainPageQuery, mps, mps.inters, v)
}

func (mps *MainPageSelect) sqlScan(ctx context.Context, root *MainPageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mps.fns))
	for _, fn := range mps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
