// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/mainpage"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MainPage is the model entity for the MainPage schema.
type MainPage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ImageID holds the value of the "image_id" field.
	ImageID uuid.UUID `json:"image_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Href holds the value of the "Href" field.
	Href string `json:"Href,omitempty"`
	// IsHidden holds the value of the "IsHidden" field.
	IsHidden bool `json:"IsHidden,omitempty"`
	// Fluid holds the value of the "fluid" field.
	Fluid        bool `json:"fluid,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MainPage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mainpage.FieldIsHidden, mainpage.FieldFluid:
			values[i] = new(sql.NullBool)
		case mainpage.FieldTitle, mainpage.FieldContent, mainpage.FieldHref:
			values[i] = new(sql.NullString)
		case mainpage.FieldID, mainpage.FieldImageID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MainPage fields.
func (mp *MainPage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mainpage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mp.ID = *value
			}
		case mainpage.FieldImageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field image_id", values[i])
			} else if value != nil {
				mp.ImageID = *value
			}
		case mainpage.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				mp.Title = value.String
			}
		case mainpage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				mp.Content = value.String
			}
		case mainpage.FieldHref:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Href", values[i])
			} else if value.Valid {
				mp.Href = value.String
			}
		case mainpage.FieldIsHidden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field IsHidden", values[i])
			} else if value.Valid {
				mp.IsHidden = value.Bool
			}
		case mainpage.FieldFluid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field fluid", values[i])
			} else if value.Valid {
				mp.Fluid = value.Bool
			}
		default:
			mp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MainPage.
// This includes values selected through modifiers, order, etc.
func (mp *MainPage) Value(name string) (ent.Value, error) {
	return mp.selectValues.Get(name)
}

// Update returns a builder for updating this MainPage.
// Note that you need to call MainPage.Unwrap() before calling this method if this MainPage
// was returned from a transaction, and the transaction was committed or rolled back.
func (mp *MainPage) Update() *MainPageUpdateOne {
	return NewMainPageClient(mp.config).UpdateOne(mp)
}

// Unwrap unwraps the MainPage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mp *MainPage) Unwrap() *MainPage {
	_tx, ok := mp.config.driver.(*txDriver)
	if !ok {
		panic("ent: MainPage is not a transactional entity")
	}
	mp.config.driver = _tx.drv
	return mp
}

// String implements the fmt.Stringer.
func (mp *MainPage) String() string {
	var builder strings.Builder
	builder.WriteString("MainPage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mp.ID))
	builder.WriteString("image_id=")
	builder.WriteString(fmt.Sprintf("%v", mp.ImageID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(mp.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(mp.Content)
	builder.WriteString(", ")
	builder.WriteString("Href=")
	builder.WriteString(mp.Href)
	builder.WriteString(", ")
	builder.WriteString("IsHidden=")
	builder.WriteString(fmt.Sprintf("%v", mp.IsHidden))
	builder.WriteString(", ")
	builder.WriteString("fluid=")
	builder.WriteString(fmt.Sprintf("%v", mp.Fluid))
	builder.WriteByte(')')
	return builder.String()
}

// MainPages is a parsable slice of MainPage.
type MainPages []*MainPage
