// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/partner"
	"SmartLeague/pkg/ent/partnerlink"
	"SmartLeague/pkg/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PartnerLinkQuery is the builder for querying PartnerLink entities.
type PartnerLinkQuery struct {
	config
	ctx         *QueryContext
	order       []partnerlink.OrderOption
	inters      []Interceptor
	predicates  []predicate.PartnerLink
	withPartner *PartnerQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PartnerLinkQuery builder.
func (plq *PartnerLinkQuery) Where(ps ...predicate.PartnerLink) *PartnerLinkQuery {
	plq.predicates = append(plq.predicates, ps...)
	return plq
}

// Limit the number of records to be returned by this query.
func (plq *PartnerLinkQuery) Limit(limit int) *PartnerLinkQuery {
	plq.ctx.Limit = &limit
	return plq
}

// Offset to start from.
func (plq *PartnerLinkQuery) Offset(offset int) *PartnerLinkQuery {
	plq.ctx.Offset = &offset
	return plq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (plq *PartnerLinkQuery) Unique(unique bool) *PartnerLinkQuery {
	plq.ctx.Unique = &unique
	return plq
}

// Order specifies how the records should be ordered.
func (plq *PartnerLinkQuery) Order(o ...partnerlink.OrderOption) *PartnerLinkQuery {
	plq.order = append(plq.order, o...)
	return plq
}

// QueryPartner chains the current query on the "partner" edge.
func (plq *PartnerLinkQuery) QueryPartner() *PartnerQuery {
	query := (&PartnerClient{config: plq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := plq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := plq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(partnerlink.Table, partnerlink.FieldID, selector),
			sqlgraph.To(partner.Table, partner.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, partnerlink.PartnerTable, partnerlink.PartnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(plq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PartnerLink entity from the query.
// Returns a *NotFoundError when no PartnerLink was found.
func (plq *PartnerLinkQuery) First(ctx context.Context) (*PartnerLink, error) {
	nodes, err := plq.Limit(1).All(setContextOp(ctx, plq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{partnerlink.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (plq *PartnerLinkQuery) FirstX(ctx context.Context) *PartnerLink {
	node, err := plq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PartnerLink ID from the query.
// Returns a *NotFoundError when no PartnerLink ID was found.
func (plq *PartnerLinkQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(1).IDs(setContextOp(ctx, plq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{partnerlink.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (plq *PartnerLinkQuery) FirstIDX(ctx context.Context) int {
	id, err := plq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PartnerLink entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PartnerLink entity is found.
// Returns a *NotFoundError when no PartnerLink entities are found.
func (plq *PartnerLinkQuery) Only(ctx context.Context) (*PartnerLink, error) {
	nodes, err := plq.Limit(2).All(setContextOp(ctx, plq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{partnerlink.Label}
	default:
		return nil, &NotSingularError{partnerlink.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (plq *PartnerLinkQuery) OnlyX(ctx context.Context) *PartnerLink {
	node, err := plq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PartnerLink ID in the query.
// Returns a *NotSingularError when more than one PartnerLink ID is found.
// Returns a *NotFoundError when no entities are found.
func (plq *PartnerLinkQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(2).IDs(setContextOp(ctx, plq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{partnerlink.Label}
	default:
		err = &NotSingularError{partnerlink.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (plq *PartnerLinkQuery) OnlyIDX(ctx context.Context) int {
	id, err := plq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PartnerLinks.
func (plq *PartnerLinkQuery) All(ctx context.Context) ([]*PartnerLink, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryAll)
	if err := plq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PartnerLink, *PartnerLinkQuery]()
	return withInterceptors[[]*PartnerLink](ctx, plq, qr, plq.inters)
}

// AllX is like All, but panics if an error occurs.
func (plq *PartnerLinkQuery) AllX(ctx context.Context) []*PartnerLink {
	nodes, err := plq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PartnerLink IDs.
func (plq *PartnerLinkQuery) IDs(ctx context.Context) (ids []int, err error) {
	if plq.ctx.Unique == nil && plq.path != nil {
		plq.Unique(true)
	}
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryIDs)
	if err = plq.Select(partnerlink.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (plq *PartnerLinkQuery) IDsX(ctx context.Context) []int {
	ids, err := plq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (plq *PartnerLinkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryCount)
	if err := plq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, plq, querierCount[*PartnerLinkQuery](), plq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (plq *PartnerLinkQuery) CountX(ctx context.Context) int {
	count, err := plq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (plq *PartnerLinkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryExist)
	switch _, err := plq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (plq *PartnerLinkQuery) ExistX(ctx context.Context) bool {
	exist, err := plq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PartnerLinkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (plq *PartnerLinkQuery) Clone() *PartnerLinkQuery {
	if plq == nil {
		return nil
	}
	return &PartnerLinkQuery{
		config:      plq.config,
		ctx:         plq.ctx.Clone(),
		order:       append([]partnerlink.OrderOption{}, plq.order...),
		inters:      append([]Interceptor{}, plq.inters...),
		predicates:  append([]predicate.PartnerLink{}, plq.predicates...),
		withPartner: plq.withPartner.Clone(),
		// clone intermediate query.
		sql:  plq.sql.Clone(),
		path: plq.path,
	}
}

// WithPartner tells the query-builder to eager-load the nodes that are connected to
// the "partner" edge. The optional arguments are used to configure the query builder of the edge.
func (plq *PartnerLinkQuery) WithPartner(opts ...func(*PartnerQuery)) *PartnerLinkQuery {
	query := (&PartnerClient{config: plq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	plq.withPartner = query
	return plq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PartnerLink.Query().
//		GroupBy(partnerlink.FieldLabel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (plq *PartnerLinkQuery) GroupBy(field string, fields ...string) *PartnerLinkGroupBy {
	plq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PartnerLinkGroupBy{build: plq}
	grbuild.flds = &plq.ctx.Fields
	grbuild.label = partnerlink.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//	}
//
//	client.PartnerLink.Query().
//		Select(partnerlink.FieldLabel).
//		Scan(ctx, &v)
func (plq *PartnerLinkQuery) Select(fields ...string) *PartnerLinkSelect {
	plq.ctx.Fields = append(plq.ctx.Fields, fields...)
	sbuild := &PartnerLinkSelect{PartnerLinkQuery: plq}
	sbuild.label = partnerlink.Label
	sbuild.flds, sbuild.scan = &plq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PartnerLinkSelect configured with the given aggregations.
func (plq *PartnerLinkQuery) Aggregate(fns ...AggregateFunc) *PartnerLinkSelect {
	return plq.Select().Aggregate(fns...)
}

func (plq *PartnerLinkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range plq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, plq); err != nil {
				return err
			}
		}
	}
	for _, f := range plq.ctx.Fields {
		if !partnerlink.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if plq.path != nil {
		prev, err := plq.path(ctx)
		if err != nil {
			return err
		}
		plq.sql = prev
	}
	return nil
}

func (plq *PartnerLinkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PartnerLink, error) {
	var (
		nodes       = []*PartnerLink{}
		withFKs     = plq.withFKs
		_spec       = plq.querySpec()
		loadedTypes = [1]bool{
			plq.withPartner != nil,
		}
	)
	if plq.withPartner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, partnerlink.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PartnerLink).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PartnerLink{config: plq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, plq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := plq.withPartner; query != nil {
		if err := plq.loadPartner(ctx, query, nodes, nil,
			func(n *PartnerLink, e *Partner) { n.Edges.Partner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (plq *PartnerLinkQuery) loadPartner(ctx context.Context, query *PartnerQuery, nodes []*PartnerLink, init func(*PartnerLink), assign func(*PartnerLink, *Partner)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PartnerLink)
	for i := range nodes {
		if nodes[i].partner_links == nil {
			continue
		}
		fk := *nodes[i].partner_links
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(partner.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "partner_links" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (plq *PartnerLinkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := plq.querySpec()
	_spec.Node.Columns = plq.ctx.Fields
	if len(plq.ctx.Fields) > 0 {
		_spec.Unique = plq.ctx.Unique != nil && *plq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, plq.driver, _spec)
}

func (plq *PartnerLinkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(partnerlink.Table, partnerlink.Columns, sqlgraph.NewFieldSpec(partnerlink.FieldID, field.TypeInt))
	_spec.From = plq.sql
	if unique := plq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if plq.path != nil {
		_spec.Unique = true
	}
	if fields := plq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerlink.FieldID)
		for i := range fields {
			if fields[i] != partnerlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := plq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := plq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := plq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := plq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (plq *PartnerLinkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(plq.driver.Dialect())
	t1 := builder.Table(partnerlink.Table)
	columns := plq.ctx.Fields
	if len(columns) == 0 {
		columns = partnerlink.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if plq.sql != nil {
		selector = plq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if plq.ctx.Unique != nil && *plq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range plq.predicates {
		p(selector)
	}
	for _, p := range plq.order {
		p(selector)
	}
	if offset := plq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := plq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PartnerLinkGroupBy is the group-by builder for PartnerLink entities.
type PartnerLinkGroupBy struct {
	selector
	build *PartnerLinkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (plgb *PartnerLinkGroupBy) Aggregate(fns ...AggregateFunc) *PartnerLinkGroupBy {
	plgb.fns = append(plgb.fns, fns...)
	return plgb
}

// Scan applies the selector query and scans the result into the given value.
func (plgb *PartnerLinkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, plgb.build.ctx, ent.OpQueryGroupBy)
	if err := plgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartnerLinkQuery, *PartnerLinkGroupBy](ctx, plgb.build, plgb, plgb.build.inters, v)
}

func (plgb *PartnerLinkGroupBy) sqlScan(ctx context.Context, root *PartnerLinkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(plgb.fns))
	for _, fn := range plgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*plgb.flds)+len(plgb.fns))
		for _, f := range *plgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*plgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := plgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PartnerLinkSelect is the builder for selecting fields of PartnerLink entities.
type PartnerLinkSelect struct {
	*PartnerLinkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pls *PartnerLinkSelect) Aggregate(fns ...AggregateFunc) *PartnerLinkSelect {
	pls.fns = append(pls.fns, fns...)
	return pls
}

// Scan applies the selector query and scans the result into the given value.
func (pls *PartnerLinkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pls.ctx, ent.OpQuerySelect)
	if err := pls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartnerLinkQuery, *PartnerLinkSelect](ctx, pls.PartnerLinkQuery, pls, pls.inters, v)
}

func (pls *PartnerLinkSelect) sqlScan(ctx context.Context, root *PartnerLinkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pls.fns))
	for _, fn := range pls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
