// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/partner"
	"SmartLeague/pkg/ent/partnerlink"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PartnerLink is the model entity for the PartnerLink schema.
type PartnerLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Href holds the value of the "href" field.
	Href string `json:"href,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PartnerLinkQuery when eager-loading is set.
	Edges         PartnerLinkEdges `json:"edges"`
	partner_links *uuid.UUID
	selectValues  sql.SelectValues
}

// PartnerLinkEdges holds the relations/edges for other nodes in the graph.
type PartnerLinkEdges struct {
	// Partner holds the value of the partner edge.
	Partner *Partner `json:"partner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PartnerOrErr returns the Partner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PartnerLinkEdges) PartnerOrErr() (*Partner, error) {
	if e.Partner != nil {
		return e.Partner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: partner.Label}
	}
	return nil, &NotLoadedError{edge: "partner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PartnerLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case partnerlink.FieldID:
			values[i] = new(sql.NullInt64)
		case partnerlink.FieldLabel, partnerlink.FieldHref:
			values[i] = new(sql.NullString)
		case partnerlink.ForeignKeys[0]: // partner_links
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PartnerLink fields.
func (pl *PartnerLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case partnerlink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pl.ID = int(value.Int64)
		case partnerlink.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				pl.Label = value.String
			}
		case partnerlink.FieldHref:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field href", values[i])
			} else if value.Valid {
				pl.Href = value.String
			}
		case partnerlink.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field partner_links", values[i])
			} else if value.Valid {
				pl.partner_links = new(uuid.UUID)
				*pl.partner_links = *value.S.(*uuid.UUID)
			}
		default:
			pl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PartnerLink.
// This includes values selected through modifiers, order, etc.
func (pl *PartnerLink) Value(name string) (ent.Value, error) {
	return pl.selectValues.Get(name)
}

// QueryPartner queries the "partner" edge of the PartnerLink entity.
func (pl *PartnerLink) QueryPartner() *PartnerQuery {
	return NewPartnerLinkClient(pl.config).QueryPartner(pl)
}

// Update returns a builder for updating this PartnerLink.
// Note that you need to call PartnerLink.Unwrap() before calling this method if this PartnerLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (pl *PartnerLink) Update() *PartnerLinkUpdateOne {
	return NewPartnerLinkClient(pl.config).UpdateOne(pl)
}

// Unwrap unwraps the PartnerLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pl *PartnerLink) Unwrap() *PartnerLink {
	_tx, ok := pl.config.driver.(*txDriver)
	if !ok {
		panic("ent: PartnerLink is not a transactional entity")
	}
	pl.config.driver = _tx.drv
	return pl
}

// String implements the fmt.Stringer.
func (pl *PartnerLink) String() string {
	var builder strings.Builder
	builder.WriteString("PartnerLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pl.ID))
	builder.WriteString("label=")
	builder.WriteString(pl.Label)
	builder.WriteString(", ")
	builder.WriteString("href=")
	builder.WriteString(pl.Href)
	builder.WriteByte(')')
	return builder.String()
}

// PartnerLinks is a parsable slice of PartnerLink.
type PartnerLinks []*PartnerLink
