// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/partner"
	"SmartLeague/pkg/ent/partnerlink"
	"SmartLeague/pkg/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PartnerLinkUpdate is the builder for updating PartnerLink entities.
type PartnerLinkUpdate struct {
	config
	hooks    []Hook
	mutation *PartnerLinkMutation
}

// Where appends a list predicates to the PartnerLinkUpdate builder.
func (plu *PartnerLinkUpdate) Where(ps ...predicate.PartnerLink) *PartnerLinkUpdate {
	plu.mutation.Where(ps...)
	return plu
}

// SetLabel sets the "label" field.
func (plu *PartnerLinkUpdate) SetLabel(s string) *PartnerLinkUpdate {
	plu.mutation.SetLabel(s)
	return plu
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (plu *PartnerLinkUpdate) SetNillableLabel(s *string) *PartnerLinkUpdate {
	if s != nil {
		plu.SetLabel(*s)
	}
	return plu
}

// SetHref sets the "href" field.
func (plu *PartnerLinkUpdate) SetHref(s string) *PartnerLinkUpdate {
	plu.mutation.SetHref(s)
	return plu
}

// SetNillableHref sets the "href" field if the given value is not nil.
func (plu *PartnerLinkUpdate) SetNillableHref(s *string) *PartnerLinkUpdate {
	if s != nil {
		plu.SetHref(*s)
	}
	return plu
}

// SetPartnerID sets the "partner" edge to the Partner entity by ID.
func (plu *PartnerLinkUpdate) SetPartnerID(id uuid.UUID) *PartnerLinkUpdate {
	plu.mutation.SetPartnerID(id)
	return plu
}

// SetPartner sets the "partner" edge to the Partner entity.
func (plu *PartnerLinkUpdate) SetPartner(p *Partner) *PartnerLinkUpdate {
	return plu.SetPartnerID(p.ID)
}

// Mutation returns the PartnerLinkMutation object of the builder.
func (plu *PartnerLinkUpdate) Mutation() *PartnerLinkMutation {
	return plu.mutation
}

// ClearPartner clears the "partner" edge to the Partner entity.
func (plu *PartnerLinkUpdate) ClearPartner() *PartnerLinkUpdate {
	plu.mutation.ClearPartner()
	return plu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (plu *PartnerLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, plu.sqlSave, plu.mutation, plu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (plu *PartnerLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := plu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (plu *PartnerLinkUpdate) Exec(ctx context.Context) error {
	_, err := plu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plu *PartnerLinkUpdate) ExecX(ctx context.Context) {
	if err := plu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (plu *PartnerLinkUpdate) check() error {
	if v, ok := plu.mutation.Label(); ok {
		if err := partnerlink.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "PartnerLink.label": %w`, err)}
		}
	}
	if v, ok := plu.mutation.Href(); ok {
		if err := partnerlink.HrefValidator(v); err != nil {
			return &ValidationError{Name: "href", err: fmt.Errorf(`ent: validator failed for field "PartnerLink.href": %w`, err)}
		}
	}
	if plu.mutation.PartnerCleared() && len(plu.mutation.PartnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PartnerLink.partner"`)
	}
	return nil
}

func (plu *PartnerLinkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := plu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(partnerlink.Table, partnerlink.Columns, sqlgraph.NewFieldSpec(partnerlink.FieldID, field.TypeInt))
	if ps := plu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := plu.mutation.Label(); ok {
		_spec.SetField(partnerlink.FieldLabel, field.TypeString, value)
	}
	if value, ok := plu.mutation.Href(); ok {
		_spec.SetField(partnerlink.FieldHref, field.TypeString, value)
	}
	if plu.mutation.PartnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   partnerlink.PartnerTable,
			Columns: []string{partnerlink.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := plu.mutation.PartnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   partnerlink.PartnerTable,
			Columns: []string{partnerlink.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, plu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	plu.mutation.done = true
	return n, nil
}

// PartnerLinkUpdateOne is the builder for updating a single PartnerLink entity.
type PartnerLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PartnerLinkMutation
}

// SetLabel sets the "label" field.
func (pluo *PartnerLinkUpdateOne) SetLabel(s string) *PartnerLinkUpdateOne {
	pluo.mutation.SetLabel(s)
	return pluo
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (pluo *PartnerLinkUpdateOne) SetNillableLabel(s *string) *PartnerLinkUpdateOne {
	if s != nil {
		pluo.SetLabel(*s)
	}
	return pluo
}

// SetHref sets the "href" field.
func (pluo *PartnerLinkUpdateOne) SetHref(s string) *PartnerLinkUpdateOne {
	pluo.mutation.SetHref(s)
	return pluo
}

// SetNillableHref sets the "href" field if the given value is not nil.
func (pluo *PartnerLinkUpdateOne) SetNillableHref(s *string) *PartnerLinkUpdateOne {
	if s != nil {
		pluo.SetHref(*s)
	}
	return pluo
}

// SetPartnerID sets the "partner" edge to the Partner entity by ID.
func (pluo *PartnerLinkUpdateOne) SetPartnerID(id uuid.UUID) *PartnerLinkUpdateOne {
	pluo.mutation.SetPartnerID(id)
	return pluo
}

// SetPartner sets the "partner" edge to the Partner entity.
func (pluo *PartnerLinkUpdateOne) SetPartner(p *Partner) *PartnerLinkUpdateOne {
	return pluo.SetPartnerID(p.ID)
}

// Mutation returns the PartnerLinkMutation object of the builder.
func (pluo *PartnerLinkUpdateOne) Mutation() *PartnerLinkMutation {
	return pluo.mutation
}

// ClearPartner clears the "partner" edge to the Partner entity.
func (pluo *PartnerLinkUpdateOne) ClearPartner() *PartnerLinkUpdateOne {
	pluo.mutation.ClearPartner()
	return pluo
}

// Where appends a list predicates to the PartnerLinkUpdate builder.
func (pluo *PartnerLinkUpdateOne) Where(ps ...predicate.PartnerLink) *PartnerLinkUpdateOne {
	pluo.mutation.Where(ps...)
	return pluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pluo *PartnerLinkUpdateOne) Select(field string, fields ...string) *PartnerLinkUpdateOne {
	pluo.fields = append([]string{field}, fields...)
	return pluo
}

// Save executes the query and returns the updated PartnerLink entity.
func (pluo *PartnerLinkUpdateOne) Save(ctx context.Context) (*PartnerLink, error) {
	return withHooks(ctx, pluo.sqlSave, pluo.mutation, pluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pluo *PartnerLinkUpdateOne) SaveX(ctx context.Context) *PartnerLink {
	node, err := pluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pluo *PartnerLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := pluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pluo *PartnerLinkUpdateOne) ExecX(ctx context.Context) {
	if err := pluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pluo *PartnerLinkUpdateOne) check() error {
	if v, ok := pluo.mutation.Label(); ok {
		if err := partnerlink.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "PartnerLink.label": %w`, err)}
		}
	}
	if v, ok := pluo.mutation.Href(); ok {
		if err := partnerlink.HrefValidator(v); err != nil {
			return &ValidationError{Name: "href", err: fmt.Errorf(`ent: validator failed for field "PartnerLink.href": %w`, err)}
		}
	}
	if pluo.mutation.PartnerCleared() && len(pluo.mutation.PartnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PartnerLink.partner"`)
	}
	return nil
}

func (pluo *PartnerLinkUpdateOne) sqlSave(ctx context.Context) (_node *PartnerLink, err error) {
	if err := pluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(partnerlink.Table, partnerlink.Columns, sqlgraph.NewFieldSpec(partnerlink.FieldID, field.TypeInt))
	id, ok := pluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PartnerLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerlink.FieldID)
		for _, f := range fields {
			if !partnerlink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != partnerlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pluo.mutation.Label(); ok {
		_spec.SetField(partnerlink.FieldLabel, field.TypeString, value)
	}
	if value, ok := pluo.mutation.Href(); ok {
		_spec.SetField(partnerlink.FieldHref, field.TypeString, value)
	}
	if pluo.mutation.PartnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   partnerlink.PartnerTable,
			Columns: []string{partnerlink.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pluo.mutation.PartnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   partnerlink.PartnerTable,
			Columns: []string{partnerlink.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PartnerLink{config: pluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pluo.mutation.done = true
	return _node, nil
}
