// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/partnerlink"
	"SmartLeague/pkg/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartnerLinkDelete is the builder for deleting a PartnerLink entity.
type PartnerLinkDelete struct {
	config
	hooks    []Hook
	mutation *PartnerLinkMutation
}

// Where appends a list predicates to the PartnerLinkDelete builder.
func (pld *PartnerLinkDelete) Where(ps ...predicate.PartnerLink) *PartnerLinkDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *PartnerLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pld.sqlExec, pld.mutation, pld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *PartnerLinkDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *PartnerLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(partnerlink.Table, sqlgraph.NewFieldSpec(partnerlink.FieldID, field.TypeInt))
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pld.mutation.done = true
	return affected, err
}

// PartnerLinkDeleteOne is the builder for deleting a single PartnerLink entity.
type PartnerLinkDeleteOne struct {
	pld *PartnerLinkDelete
}

// Where appends a list predicates to the PartnerLinkDelete builder.
func (pldo *PartnerLinkDeleteOne) Where(ps ...predicate.PartnerLink) *PartnerLinkDeleteOne {
	pldo.pld.mutation.Where(ps...)
	return pldo
}

// Exec executes the deletion query.
func (pldo *PartnerLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{partnerlink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *PartnerLinkDeleteOne) ExecX(ctx context.Context) {
	if err := pldo.Exec(ctx); err != nil {
		panic(err)
	}
}
