// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/pkg/ent/partner"
	"SmartLeague/pkg/ent/partnerlink"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PartnerLinkCreate is the builder for creating a PartnerLink entity.
type PartnerLinkCreate struct {
	config
	mutation *PartnerLinkMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (plc *PartnerLinkCreate) SetLabel(s string) *PartnerLinkCreate {
	plc.mutation.SetLabel(s)
	return plc
}

// SetHref sets the "href" field.
func (plc *PartnerLinkCreate) SetHref(s string) *PartnerLinkCreate {
	plc.mutation.SetHref(s)
	return plc
}

// SetPartnerID sets the "partner" edge to the Partner entity by ID.
func (plc *PartnerLinkCreate) SetPartnerID(id uuid.UUID) *PartnerLinkCreate {
	plc.mutation.SetPartnerID(id)
	return plc
}

// SetPartner sets the "partner" edge to the Partner entity.
func (plc *PartnerLinkCreate) SetPartner(p *Partner) *PartnerLinkCreate {
	return plc.SetPartnerID(p.ID)
}

// Mutation returns the PartnerLinkMutation object of the builder.
func (plc *PartnerLinkCreate) Mutation() *PartnerLinkMutation {
	return plc.mutation
}

// Save creates the PartnerLink in the database.
func (plc *PartnerLinkCreate) Save(ctx context.Context) (*PartnerLink, error) {
	return withHooks(ctx, plc.sqlSave, plc.mutation, plc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (plc *PartnerLinkCreate) SaveX(ctx context.Context) *PartnerLink {
	v, err := plc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plc *PartnerLinkCreate) Exec(ctx context.Context) error {
	_, err := plc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plc *PartnerLinkCreate) ExecX(ctx context.Context) {
	if err := plc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (plc *PartnerLinkCreate) check() error {
	if _, ok := plc.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "PartnerLink.label"`)}
	}
	if v, ok := plc.mutation.Label(); ok {
		if err := partnerlink.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "PartnerLink.label": %w`, err)}
		}
	}
	if _, ok := plc.mutation.Href(); !ok {
		return &ValidationError{Name: "href", err: errors.New(`ent: missing required field "PartnerLink.href"`)}
	}
	if v, ok := plc.mutation.Href(); ok {
		if err := partnerlink.HrefValidator(v); err != nil {
			return &ValidationError{Name: "href", err: fmt.Errorf(`ent: validator failed for field "PartnerLink.href": %w`, err)}
		}
	}
	if len(plc.mutation.PartnerIDs()) == 0 {
		return &ValidationError{Name: "partner", err: errors.New(`ent: missing required edge "PartnerLink.partner"`)}
	}
	return nil
}

func (plc *PartnerLinkCreate) sqlSave(ctx context.Context) (*PartnerLink, error) {
	if err := plc.check(); err != nil {
		return nil, err
	}
	_node, _spec := plc.createSpec()
	if err := sqlgraph.CreateNode(ctx, plc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	plc.mutation.id = &_node.ID
	plc.mutation.done = true
	return _node, nil
}

func (plc *PartnerLinkCreate) createSpec() (*PartnerLink, *sqlgraph.CreateSpec) {
	var (
		_node = &PartnerLink{config: plc.config}
		_spec = sqlgraph.NewCreateSpec(partnerlink.Table, sqlgraph.NewFieldSpec(partnerlink.FieldID, field.TypeInt))
	)
	if value, ok := plc.mutation.Label(); ok {
		_spec.SetField(partnerlink.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := plc.mutation.Href(); ok {
		_spec.SetField(partnerlink.FieldHref, field.TypeString, value)
		_node.Href = value
	}
	if nodes := plc.mutation.PartnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   partnerlink.PartnerTable,
			Columns: []string{partnerlink.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.partner_links = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PartnerLinkCreateBulk is the builder for creating many PartnerLink entities in bulk.
type PartnerLinkCreateBulk struct {
	config
	err      error
	builders []*PartnerLinkCreate
}

// Save creates the PartnerLink entities in the database.
func (plcb *PartnerLinkCreateBulk) Save(ctx context.Context) ([]*PartnerLink, error) {
	if plcb.err != nil {
		return nil, plcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(plcb.builders))
	nodes := make([]*PartnerLink, len(plcb.builders))
	mutators := make([]Mutator, len(plcb.builders))
	for i := range plcb.builders {
		func(i int, root context.Context) {
			builder := plcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PartnerLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, plcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, plcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, plcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (plcb *PartnerLinkCreateBulk) SaveX(ctx context.Context) []*PartnerLink {
	v, err := plcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plcb *PartnerLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := plcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plcb *PartnerLinkCreateBulk) ExecX(ctx context.Context) {
	if err := plcb.Exec(ctx); err != nil {
		panic(err)
	}
}
