// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SmartLeague/internal/domain/schema"
	"SmartLeague/internal/domain/types"
	"SmartLeague/pkg/ent/category"
	"SmartLeague/pkg/ent/cosmetics"
	"SmartLeague/pkg/ent/mainpage"
	"SmartLeague/pkg/ent/news"
	"SmartLeague/pkg/ent/partner"
	"SmartLeague/pkg/ent/partnerlink"
	"SmartLeague/pkg/ent/refreshtoken"
	"SmartLeague/pkg/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[2].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	cosmeticsFields := schema.Cosmetics{}.Fields()
	_ = cosmeticsFields
	// cosmeticsDescTitle is the schema descriptor for title field.
	cosmeticsDescTitle := cosmeticsFields[2].Descriptor()
	// cosmetics.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	cosmetics.TitleValidator = cosmeticsDescTitle.Validators[0].(func(string) error)
	// cosmeticsDescVolume is the schema descriptor for volume field.
	cosmeticsDescVolume := cosmeticsFields[5].Descriptor()
	// cosmetics.VolumeValidator is a validator for the "volume" field. It is called by the builders before save.
	cosmetics.VolumeValidator = cosmeticsDescVolume.Validators[0].(func(int) error)
	// cosmeticsDescID is the schema descriptor for id field.
	cosmeticsDescID := cosmeticsFields[0].Descriptor()
	// cosmetics.DefaultID holds the default value on creation for the id field.
	cosmetics.DefaultID = cosmeticsDescID.Default.(func() uuid.UUID)
	mainpageFields := schema.MainPage{}.Fields()
	_ = mainpageFields
	// mainpageDescTitle is the schema descriptor for title field.
	mainpageDescTitle := mainpageFields[2].Descriptor()
	// mainpage.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	mainpage.TitleValidator = mainpageDescTitle.Validators[0].(func(string) error)
	// mainpageDescContent is the schema descriptor for content field.
	mainpageDescContent := mainpageFields[3].Descriptor()
	// mainpage.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	mainpage.ContentValidator = mainpageDescContent.Validators[0].(func(string) error)
	// mainpageDescHref is the schema descriptor for Href field.
	mainpageDescHref := mainpageFields[4].Descriptor()
	// mainpage.HrefValidator is a validator for the "Href" field. It is called by the builders before save.
	mainpage.HrefValidator = mainpageDescHref.Validators[0].(func(string) error)
	// mainpageDescIsHidden is the schema descriptor for IsHidden field.
	mainpageDescIsHidden := mainpageFields[5].Descriptor()
	// mainpage.DefaultIsHidden holds the default value on creation for the IsHidden field.
	mainpage.DefaultIsHidden = mainpageDescIsHidden.Default.(bool)
	// mainpageDescFluid is the schema descriptor for fluid field.
	mainpageDescFluid := mainpageFields[6].Descriptor()
	// mainpage.DefaultFluid holds the default value on creation for the fluid field.
	mainpage.DefaultFluid = mainpageDescFluid.Default.(bool)
	// mainpageDescID is the schema descriptor for id field.
	mainpageDescID := mainpageFields[0].Descriptor()
	// mainpage.DefaultID holds the default value on creation for the id field.
	mainpage.DefaultID = mainpageDescID.Default.(func() uuid.UUID)
	newsFields := schema.News{}.Fields()
	_ = newsFields
	// newsDescTitle is the schema descriptor for title field.
	newsDescTitle := newsFields[2].Descriptor()
	// news.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	news.TitleValidator = newsDescTitle.Validators[0].(func(string) error)
	// newsDescContent is the schema descriptor for content field.
	newsDescContent := newsFields[3].Descriptor()
	// news.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	news.ContentValidator = newsDescContent.Validators[0].(func(string) error)
	// newsDescID is the schema descriptor for id field.
	newsDescID := newsFields[0].Descriptor()
	// news.DefaultID holds the default value on creation for the id field.
	news.DefaultID = newsDescID.Default.(func() uuid.UUID)
	partnerFields := schema.Partner{}.Fields()
	_ = partnerFields
	// partnerDescName is the schema descriptor for name field.
	partnerDescName := partnerFields[1].Descriptor()
	// partner.NameValidator is a validator for the "name" field. It is called by the builders before save.
	partner.NameValidator = func() func(string) error {
		validators := partnerDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// partnerDescDescription is the schema descriptor for description field.
	partnerDescDescription := partnerFields[2].Descriptor()
	// partner.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	partner.DescriptionValidator = partnerDescDescription.Validators[0].(func(string) error)
	// partnerDescID is the schema descriptor for id field.
	partnerDescID := partnerFields[0].Descriptor()
	// partner.DefaultID holds the default value on creation for the id field.
	partner.DefaultID = partnerDescID.Default.(func() uuid.UUID)
	partnerlinkFields := schema.PartnerLink{}.Fields()
	_ = partnerlinkFields
	// partnerlinkDescLabel is the schema descriptor for label field.
	partnerlinkDescLabel := partnerlinkFields[0].Descriptor()
	// partnerlink.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	partnerlink.LabelValidator = partnerlinkDescLabel.Validators[0].(func(string) error)
	// partnerlinkDescHref is the schema descriptor for href field.
	partnerlinkDescHref := partnerlinkFields[1].Descriptor()
	// partnerlink.HrefValidator is a validator for the "href" field. It is called by the builders before save.
	partnerlink.HrefValidator = partnerlinkDescHref.Validators[0].(func(string) error)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescJti is the schema descriptor for jti field.
	refreshtokenDescJti := refreshtokenFields[1].Descriptor()
	// refreshtoken.JtiValidator is a validator for the "jti" field. It is called by the builders before save.
	refreshtoken.JtiValidator = refreshtokenDescJti.Validators[0].(func(string) error)
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenFields[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescSurname is the schema descriptor for surname field.
	userDescSurname := userFields[4].Descriptor()
	// user.SurnameValidator is a validator for the "surname" field. It is called by the builders before save.
	user.SurnameValidator = func() func(string) error {
		validators := userDescSurname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(surname string) error {
			for _, fn := range fns {
				if err := fn(surname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[5].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = types.Role(userDescRole.Default.(int))
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
