/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as SeriesCreateRouteImport } from './routes/series.create'
import { Route as SeriesIdRouteImport } from './routes/series.$id'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as ClubsCreateRouteImport } from './routes/clubs.create'
import { Route as ClubsIdRouteImport } from './routes/clubs.$id'
import { Route as UserIdSeriesRouteImport } from './routes/user.$id.series'
import { Route as UserIdGamesRouteImport } from './routes/user.$id.games'
import { Route as SeriesIdManageRouteImport } from './routes/series.$id.manage'
import { Route as GameIdManageRouteImport } from './routes/game.$id.manage'
import { Route as ClubsIdSeriesRouteImport } from './routes/clubs.$id.series'
import { Route as ClubsIdMembersRouteImport } from './routes/clubs.$id.members'
import { Route as ClubsIdManageRouteImport } from './routes/clubs.$id.manage'
import { Route as ClubsIdGamesRouteImport } from './routes/clubs.$id.games'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesCreateRoute = SeriesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SeriesRoute,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SeriesRoute,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsCreateRoute = ClubsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ClubsRoute,
} as any)
const ClubsIdRoute = ClubsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClubsRoute,
} as any)
const UserIdSeriesRoute = UserIdSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => UserIdRoute,
} as any)
const UserIdGamesRoute = UserIdGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => UserIdRoute,
} as any)
const SeriesIdManageRoute = SeriesIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => SeriesIdRoute,
} as any)
const GameIdManageRoute = GameIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => GameIdRoute,
} as any)
const ClubsIdSeriesRoute = ClubsIdSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => ClubsIdRoute,
} as any)
const ClubsIdMembersRoute = ClubsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ClubsIdRoute,
} as any)
const ClubsIdManageRoute = ClubsIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ClubsIdRoute,
} as any)
const ClubsIdGamesRoute = ClubsIdGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => ClubsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/register': typeof RegisterRoute
  '/series': typeof SeriesRouteWithChildren
  '/clubs/$id': typeof ClubsIdRouteWithChildren
  '/clubs/create': typeof ClubsCreateRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/series/$id': typeof SeriesIdRouteWithChildren
  '/series/create': typeof SeriesCreateRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/clubs/$id/games': typeof ClubsIdGamesRoute
  '/clubs/$id/manage': typeof ClubsIdManageRoute
  '/clubs/$id/members': typeof ClubsIdMembersRoute
  '/clubs/$id/series': typeof ClubsIdSeriesRoute
  '/game/$id/manage': typeof GameIdManageRoute
  '/series/$id/manage': typeof SeriesIdManageRoute
  '/user/$id/games': typeof UserIdGamesRoute
  '/user/$id/series': typeof UserIdSeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/register': typeof RegisterRoute
  '/series': typeof SeriesRouteWithChildren
  '/clubs/$id': typeof ClubsIdRouteWithChildren
  '/clubs/create': typeof ClubsCreateRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/series/$id': typeof SeriesIdRouteWithChildren
  '/series/create': typeof SeriesCreateRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/clubs/$id/games': typeof ClubsIdGamesRoute
  '/clubs/$id/manage': typeof ClubsIdManageRoute
  '/clubs/$id/members': typeof ClubsIdMembersRoute
  '/clubs/$id/series': typeof ClubsIdSeriesRoute
  '/game/$id/manage': typeof GameIdManageRoute
  '/series/$id/manage': typeof SeriesIdManageRoute
  '/user/$id/games': typeof UserIdGamesRoute
  '/user/$id/series': typeof UserIdSeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/register': typeof RegisterRoute
  '/series': typeof SeriesRouteWithChildren
  '/clubs/$id': typeof ClubsIdRouteWithChildren
  '/clubs/create': typeof ClubsCreateRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/series/$id': typeof SeriesIdRouteWithChildren
  '/series/create': typeof SeriesCreateRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/clubs/$id/games': typeof ClubsIdGamesRoute
  '/clubs/$id/manage': typeof ClubsIdManageRoute
  '/clubs/$id/members': typeof ClubsIdMembersRoute
  '/clubs/$id/series': typeof ClubsIdSeriesRoute
  '/game/$id/manage': typeof GameIdManageRoute
  '/series/$id/manage': typeof SeriesIdManageRoute
  '/user/$id/games': typeof UserIdGamesRoute
  '/user/$id/series': typeof UserIdSeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/clubs'
    | '/login'
    | '/players'
    | '/register'
    | '/series'
    | '/clubs/$id'
    | '/clubs/create'
    | '/game/$id'
    | '/series/$id'
    | '/series/create'
    | '/user/$id'
    | '/clubs/$id/games'
    | '/clubs/$id/manage'
    | '/clubs/$id/members'
    | '/clubs/$id/series'
    | '/game/$id/manage'
    | '/series/$id/manage'
    | '/user/$id/games'
    | '/user/$id/series'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/clubs'
    | '/login'
    | '/players'
    | '/register'
    | '/series'
    | '/clubs/$id'
    | '/clubs/create'
    | '/game/$id'
    | '/series/$id'
    | '/series/create'
    | '/user/$id'
    | '/clubs/$id/games'
    | '/clubs/$id/manage'
    | '/clubs/$id/members'
    | '/clubs/$id/series'
    | '/game/$id/manage'
    | '/series/$id/manage'
    | '/user/$id/games'
    | '/user/$id/series'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/clubs'
    | '/login'
    | '/players'
    | '/register'
    | '/series'
    | '/clubs/$id'
    | '/clubs/create'
    | '/game/$id'
    | '/series/$id'
    | '/series/create'
    | '/user/$id'
    | '/clubs/$id/games'
    | '/clubs/$id/manage'
    | '/clubs/$id/members'
    | '/clubs/$id/series'
    | '/game/$id/manage'
    | '/series/$id/manage'
    | '/user/$id/games'
    | '/user/$id/series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayersRoute: typeof PlayersRoute
  RegisterRoute: typeof RegisterRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  GameIdRoute: typeof GameIdRouteWithChildren
  UserIdRoute: typeof UserIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/create': {
      id: '/series/create'
      path: '/create'
      fullPath: '/series/create'
      preLoaderRoute: typeof SeriesCreateRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/create': {
      id: '/clubs/create'
      path: '/create'
      fullPath: '/clubs/create'
      preLoaderRoute: typeof ClubsCreateRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/clubs/$id': {
      id: '/clubs/$id'
      path: '/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof ClubsIdRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/user/$id/series': {
      id: '/user/$id/series'
      path: '/series'
      fullPath: '/user/$id/series'
      preLoaderRoute: typeof UserIdSeriesRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/user/$id/games': {
      id: '/user/$id/games'
      path: '/games'
      fullPath: '/user/$id/games'
      preLoaderRoute: typeof UserIdGamesRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/series/$id/manage': {
      id: '/series/$id/manage'
      path: '/manage'
      fullPath: '/series/$id/manage'
      preLoaderRoute: typeof SeriesIdManageRouteImport
      parentRoute: typeof SeriesIdRoute
    }
    '/game/$id/manage': {
      id: '/game/$id/manage'
      path: '/manage'
      fullPath: '/game/$id/manage'
      preLoaderRoute: typeof GameIdManageRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/clubs/$id/series': {
      id: '/clubs/$id/series'
      path: '/series'
      fullPath: '/clubs/$id/series'
      preLoaderRoute: typeof ClubsIdSeriesRouteImport
      parentRoute: typeof ClubsIdRoute
    }
    '/clubs/$id/members': {
      id: '/clubs/$id/members'
      path: '/members'
      fullPath: '/clubs/$id/members'
      preLoaderRoute: typeof ClubsIdMembersRouteImport
      parentRoute: typeof ClubsIdRoute
    }
    '/clubs/$id/manage': {
      id: '/clubs/$id/manage'
      path: '/manage'
      fullPath: '/clubs/$id/manage'
      preLoaderRoute: typeof ClubsIdManageRouteImport
      parentRoute: typeof ClubsIdRoute
    }
    '/clubs/$id/games': {
      id: '/clubs/$id/games'
      path: '/games'
      fullPath: '/clubs/$id/games'
      preLoaderRoute: typeof ClubsIdGamesRouteImport
      parentRoute: typeof ClubsIdRoute
    }
  }
}

interface ClubsIdRouteChildren {
  ClubsIdGamesRoute: typeof ClubsIdGamesRoute
  ClubsIdManageRoute: typeof ClubsIdManageRoute
  ClubsIdMembersRoute: typeof ClubsIdMembersRoute
  ClubsIdSeriesRoute: typeof ClubsIdSeriesRoute
}

const ClubsIdRouteChildren: ClubsIdRouteChildren = {
  ClubsIdGamesRoute: ClubsIdGamesRoute,
  ClubsIdManageRoute: ClubsIdManageRoute,
  ClubsIdMembersRoute: ClubsIdMembersRoute,
  ClubsIdSeriesRoute: ClubsIdSeriesRoute,
}

const ClubsIdRouteWithChildren =
  ClubsIdRoute._addFileChildren(ClubsIdRouteChildren)

interface ClubsRouteChildren {
  ClubsIdRoute: typeof ClubsIdRouteWithChildren
  ClubsCreateRoute: typeof ClubsCreateRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsIdRoute: ClubsIdRouteWithChildren,
  ClubsCreateRoute: ClubsCreateRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface SeriesIdRouteChildren {
  SeriesIdManageRoute: typeof SeriesIdManageRoute
}

const SeriesIdRouteChildren: SeriesIdRouteChildren = {
  SeriesIdManageRoute: SeriesIdManageRoute,
}

const SeriesIdRouteWithChildren = SeriesIdRoute._addFileChildren(
  SeriesIdRouteChildren,
)

interface SeriesRouteChildren {
  SeriesIdRoute: typeof SeriesIdRouteWithChildren
  SeriesCreateRoute: typeof SeriesCreateRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesIdRoute: SeriesIdRouteWithChildren,
  SeriesCreateRoute: SeriesCreateRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

interface GameIdRouteChildren {
  GameIdManageRoute: typeof GameIdManageRoute
}

const GameIdRouteChildren: GameIdRouteChildren = {
  GameIdManageRoute: GameIdManageRoute,
}

const GameIdRouteWithChildren =
  GameIdRoute._addFileChildren(GameIdRouteChildren)

interface UserIdRouteChildren {
  UserIdGamesRoute: typeof UserIdGamesRoute
  UserIdSeriesRoute: typeof UserIdSeriesRoute
}

const UserIdRouteChildren: UserIdRouteChildren = {
  UserIdGamesRoute: UserIdGamesRoute,
  UserIdSeriesRoute: UserIdSeriesRoute,
}

const UserIdRouteWithChildren =
  UserIdRoute._addFileChildren(UserIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ClubsRoute: ClubsRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayersRoute: PlayersRoute,
  RegisterRoute: RegisterRoute,
  SeriesRoute: SeriesRouteWithChildren,
  GameIdRoute: GameIdRouteWithChildren,
  UserIdRoute: UserIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
