// Code generated by ent, DO NOT EDIT.

package mainpage

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the mainpage type in the database.
	Label = "main_page"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImageID holds the string denoting the image_id field in the database.
	FieldImageID = "image_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldHref holds the string denoting the href field in the database.
	FieldHref = "href"
	// FieldIsHidden holds the string denoting the ishidden field in the database.
	FieldIsHidden = "is_hidden"
	// FieldFluid holds the string denoting the fluid field in the database.
	FieldFluid = "fluid"
	// Table holds the table name of the mainpage in the database.
	Table = "main_pages"
)

// Columns holds all SQL columns for mainpage fields.
var Columns = []string{
	FieldID,
	FieldImageID,
	FieldTitle,
	FieldContent,
	FieldHref,
	FieldIsHidden,
	FieldFluid,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// HrefValidator is a validator for the "Href" field. It is called by the builders before save.
	HrefValidator func(string) error
	// DefaultIsHidden holds the default value on creation for the "IsHidden" field.
	DefaultIsHidden bool
	// DefaultFluid holds the default value on creation for the "fluid" field.
	DefaultFluid bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MainPage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImageID orders the results by the image_id field.
func ByImageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByHref orders the results by the Href field.
func ByHref(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHref, opts...).ToFunc()
}

// ByIsHidden orders the results by the IsHidden field.
func ByIsHidden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsHidden, opts...).ToFunc()
}

// ByFluid orders the results by the fluid field.
func ByFluid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFluid, opts...).ToFunc()
}
