// Code generated by ent, DO NOT EDIT.

package mainpage

import (
	"SmartLeague/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldLTE(FieldID, id))
}

// ImageID applies equality check predicate on the "image_id" field. It's identical to ImageIDEQ.
func ImageID(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldImageID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldContent, v))
}

// Href applies equality check predicate on the "Href" field. It's identical to HrefEQ.
func Href(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldHref, v))
}

// IsHidden applies equality check predicate on the "IsHidden" field. It's identical to IsHiddenEQ.
func IsHidden(v bool) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldIsHidden, v))
}

// Fluid applies equality check predicate on the "fluid" field. It's identical to FluidEQ.
func Fluid(v bool) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldFluid, v))
}

// ImageIDEQ applies the EQ predicate on the "image_id" field.
func ImageIDEQ(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldImageID, v))
}

// ImageIDNEQ applies the NEQ predicate on the "image_id" field.
func ImageIDNEQ(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldImageID, v))
}

// ImageIDIn applies the In predicate on the "image_id" field.
func ImageIDIn(vs ...uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldIn(FieldImageID, vs...))
}

// ImageIDNotIn applies the NotIn predicate on the "image_id" field.
func ImageIDNotIn(vs ...uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldNotIn(FieldImageID, vs...))
}

// ImageIDGT applies the GT predicate on the "image_id" field.
func ImageIDGT(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldGT(FieldImageID, v))
}

// ImageIDGTE applies the GTE predicate on the "image_id" field.
func ImageIDGTE(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldGTE(FieldImageID, v))
}

// ImageIDLT applies the LT predicate on the "image_id" field.
func ImageIDLT(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldLT(FieldImageID, v))
}

// ImageIDLTE applies the LTE predicate on the "image_id" field.
func ImageIDLTE(v uuid.UUID) predicate.MainPage {
	return predicate.MainPage(sql.FieldLTE(FieldImageID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.MainPage {
	return predicate.MainPage(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.MainPage {
	return predicate.MainPage(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.MainPage {
	return predicate.MainPage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.MainPage {
	return predicate.MainPage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldContainsFold(FieldContent, v))
}

// HrefEQ applies the EQ predicate on the "Href" field.
func HrefEQ(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldHref, v))
}

// HrefNEQ applies the NEQ predicate on the "Href" field.
func HrefNEQ(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldHref, v))
}

// HrefIn applies the In predicate on the "Href" field.
func HrefIn(vs ...string) predicate.MainPage {
	return predicate.MainPage(sql.FieldIn(FieldHref, vs...))
}

// HrefNotIn applies the NotIn predicate on the "Href" field.
func HrefNotIn(vs ...string) predicate.MainPage {
	return predicate.MainPage(sql.FieldNotIn(FieldHref, vs...))
}

// HrefGT applies the GT predicate on the "Href" field.
func HrefGT(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldGT(FieldHref, v))
}

// HrefGTE applies the GTE predicate on the "Href" field.
func HrefGTE(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldGTE(FieldHref, v))
}

// HrefLT applies the LT predicate on the "Href" field.
func HrefLT(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldLT(FieldHref, v))
}

// HrefLTE applies the LTE predicate on the "Href" field.
func HrefLTE(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldLTE(FieldHref, v))
}

// HrefContains applies the Contains predicate on the "Href" field.
func HrefContains(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldContains(FieldHref, v))
}

// HrefHasPrefix applies the HasPrefix predicate on the "Href" field.
func HrefHasPrefix(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldHasPrefix(FieldHref, v))
}

// HrefHasSuffix applies the HasSuffix predicate on the "Href" field.
func HrefHasSuffix(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldHasSuffix(FieldHref, v))
}

// HrefEqualFold applies the EqualFold predicate on the "Href" field.
func HrefEqualFold(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldEqualFold(FieldHref, v))
}

// HrefContainsFold applies the ContainsFold predicate on the "Href" field.
func HrefContainsFold(v string) predicate.MainPage {
	return predicate.MainPage(sql.FieldContainsFold(FieldHref, v))
}

// IsHiddenEQ applies the EQ predicate on the "IsHidden" field.
func IsHiddenEQ(v bool) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldIsHidden, v))
}

// IsHiddenNEQ applies the NEQ predicate on the "IsHidden" field.
func IsHiddenNEQ(v bool) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldIsHidden, v))
}

// FluidEQ applies the EQ predicate on the "fluid" field.
func FluidEQ(v bool) predicate.MainPage {
	return predicate.MainPage(sql.FieldEQ(FieldFluid, v))
}

// FluidNEQ applies the NEQ predicate on the "fluid" field.
func FluidNEQ(v bool) predicate.MainPage {
	return predicate.MainPage(sql.FieldNEQ(FieldFluid, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MainPage) predicate.MainPage {
	return predicate.MainPage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MainPage) predicate.MainPage {
	return predicate.MainPage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MainPage) predicate.MainPage {
	return predicate.MainPage(sql.NotPredicates(p))
}
