// Code generated by ent, DO NOT EDIT.

package partnerlink

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the partnerlink type in the database.
	Label = "partner_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldHref holds the string denoting the href field in the database.
	FieldHref = "href"
	// EdgePartner holds the string denoting the partner edge name in mutations.
	EdgePartner = "partner"
	// Table holds the table name of the partnerlink in the database.
	Table = "partner_links"
	// PartnerTable is the table that holds the partner relation/edge.
	PartnerTable = "partner_links"
	// PartnerInverseTable is the table name for the Partner entity.
	// It exists in this package in order to avoid circular dependency with the "partner" package.
	PartnerInverseTable = "partners"
	// PartnerColumn is the table column denoting the partner relation/edge.
	PartnerColumn = "partner_links"
)

// Columns holds all SQL columns for partnerlink fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldHref,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "partner_links"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"partner_links",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// HrefValidator is a validator for the "href" field. It is called by the builders before save.
	HrefValidator func(string) error
)

// OrderOption defines the ordering options for the PartnerLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByHref orders the results by the href field.
func ByHref(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHref, opts...).ToFunc()
}

// ByPartnerField orders the results by partner field.
func ByPartnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPartnerStep(), sql.OrderByField(field, opts...))
	}
}
func newPartnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PartnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PartnerTable, PartnerColumn),
	)
}
