// Code generated by ent, DO NOT EDIT.

package partnerlink

import (
	"SmartLeague/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldLTE(FieldID, id))
}

// Href applies equality check predicate on the "href" field. It's identical to HrefEQ.
func Href(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEQ(FieldHref, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldContainsFold(FieldLabel, v))
}

// HrefEQ applies the EQ predicate on the "href" field.
func HrefEQ(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEQ(FieldHref, v))
}

// HrefNEQ applies the NEQ predicate on the "href" field.
func HrefNEQ(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldNEQ(FieldHref, v))
}

// HrefIn applies the In predicate on the "href" field.
func HrefIn(vs ...string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldIn(FieldHref, vs...))
}

// HrefNotIn applies the NotIn predicate on the "href" field.
func HrefNotIn(vs ...string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldNotIn(FieldHref, vs...))
}

// HrefGT applies the GT predicate on the "href" field.
func HrefGT(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldGT(FieldHref, v))
}

// HrefGTE applies the GTE predicate on the "href" field.
func HrefGTE(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldGTE(FieldHref, v))
}

// HrefLT applies the LT predicate on the "href" field.
func HrefLT(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldLT(FieldHref, v))
}

// HrefLTE applies the LTE predicate on the "href" field.
func HrefLTE(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldLTE(FieldHref, v))
}

// HrefContains applies the Contains predicate on the "href" field.
func HrefContains(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldContains(FieldHref, v))
}

// HrefHasPrefix applies the HasPrefix predicate on the "href" field.
func HrefHasPrefix(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldHasPrefix(FieldHref, v))
}

// HrefHasSuffix applies the HasSuffix predicate on the "href" field.
func HrefHasSuffix(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldHasSuffix(FieldHref, v))
}

// HrefEqualFold applies the EqualFold predicate on the "href" field.
func HrefEqualFold(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldEqualFold(FieldHref, v))
}

// HrefContainsFold applies the ContainsFold predicate on the "href" field.
func HrefContainsFold(v string) predicate.PartnerLink {
	return predicate.PartnerLink(sql.FieldContainsFold(FieldHref, v))
}

// HasPartner applies the HasEdge predicate on the "partner" edge.
func HasPartner() predicate.PartnerLink {
	return predicate.PartnerLink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PartnerTable, PartnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPartnerWith applies the HasEdge predicate on the "partner" edge with a given conditions (other predicates).
func HasPartnerWith(preds ...predicate.Partner) predicate.PartnerLink {
	return predicate.PartnerLink(func(s *sql.Selector) {
		step := newPartnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PartnerLink) predicate.PartnerLink {
	return predicate.PartnerLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PartnerLink) predicate.PartnerLink {
	return predicate.PartnerLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PartnerLink) predicate.PartnerLink {
	return predicate.PartnerLink(sql.NotPredicates(p))
}
